name: Check deps for vulnerabilities

on:
  workflow_call:
    secrets:
      NVD_API_TOKEN:
        required: true
  push:
    branches: ["*"]
  schedule:
    - cron: '0 1 * * 1,2,3,4,5' # every workday

jobs:
  deps:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '18'

    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: "~/.m2"
        key: "${{ runner.os }}-${{ hashFiles('pom.xml') }}-m2-nvd"

    - name: Cache NVD database
      uses: actions/cache@v4
      with:
        path: "~/.m2/repository/org/owasp/dependency-check-utils/*/data"
        key: "${{ runner.os }}-nvd"

    - env:
        NVD_API_TOKEN: ${{ secrets.NVD_API_TOKEN }}
      if: ${{ env.NVD_API_TOKEN == '' }}
      run: echo "NVD_API_TOKEN secret is empty"; exit 1

    - name: run dependency-check
      env:
        NVD_API_TOKEN: ${{ secrets.NVD_API_TOKEN }}
      run: |
        mvn org.owasp:dependency-check-maven:check
